# Generated by Django 3.2.5 on 2021-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('quantity', 'quantity')], max_length=250),
        ),
    ]
