# Generated by Django 3.2.5 on 2021-09-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
