# Generated by Django 3.2.5 on 2021-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20210926_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
