# Generated by Django 3.1 on 2021-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
