# Generated by Django 3.1 on 2021-08-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210818_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
    ]
